name: Carpenter in Milano
pygments: true
permalink: /articles/:year/:month/:day/:title.html

paginate: 5
paginate_path: /articles/page-:num

timezone: Asia/Beijing
navigation:
- text: ABOUT ME
  active: about
  url: /
- text: ARTICLES
  active: articles
  url: /articles
- text: CONTACT
  active: contact
  url: /contact