name: Carpenter in Milano
pygments: true
permalink: /articles/:year/:month/:day/:title.html

paginate: 5
paginate_path: /articles/page-:num

markdown: kramdown

timezone: Asia/Beijing
navigation:
- text: ABOUT ME
  active: about
  url: /
- text: ARTICLES
  active: articles
  url: /articles
- text: CONTACT
  active: contact
  url: /contact

images: http://carpenter.qiniudn.com
thumbs: http://carpenter-thumbs.qiniudn.com
description: Zhou Nie Lin's personal blog.周涅林的个人博客
url: http://clever-lin.tk
